name: Generate terraform docs
on:
  pull_request:
    branches: 
    - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: .
        recursive: true
        recursive-path: terraform/environments
        output-file: README.md
        output-method: inject
        
    - uses: planetscale/ghcommit-action@v0.1.6
      with:
        commit_message: "terraform-docs: automated action"
        repo: ${{ github.repository }}
        branch: ${{ github.head_ref || github.ref_name }}
        file_pattern: 'terraform/environments/**/README.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}